spring:
  application:
    name: cs-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #阿里oss配置
    alicloud:
      access-key: 使用自己的
      secret-key: 使用自己的
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: cs-lend
server:
  port: 14000