server:
  port: 8000 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cs_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
      username: root
      password: 123456
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  header: Authorization
  tokenSecret: qazxswedcvfrtgbnhyujmkiolp #密钥
  tokenExpired: 3600000 #token过期时间(30分钟)